C:\Users\felip>cd C:\Tinf\programacion\proyectos\desafios_django\semana 1

C:\Tinf\programacion\proyectos\desafios_django\semana 1>git add .

C:\Tinf\programacion\proyectos\desafios_django\semana 1>git push
Everything up-to-date

C:\Tinf\programacion\proyectos\desafios_django\semana 1>cd C:\Tinf\programacion\proyectos\desafios_django

C:\Tinf\programacion\proyectos\desafios_django> mkdir semana-1

C:\Tinf\programacion\proyectos\desafios_django>ls
"ls" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

C:\Tinf\programacion\proyectos\desafios_django>cd C:\Tinf\programacion\proyectos\desafios_django\semana 1

C:\Tinf\programacion\proyectos\desafios_django\semana 1>python manage.py runserver
python: can't open file 'C:\\Tinf\\programacion\\proyectos\\desafios_django\\semana 1\\manage.py': [Errno 2] No such file or directory

C:\Tinf\programacion\proyectos\desafios_django\semana 1>cd C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb

C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>env\Scripts\activate
El sistema no puede encontrar la ruta especificada.

C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>env\Scripts\activate
El sistema no puede encontrar la ruta especificada.

C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>python -m venv env

C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>
C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>env\Scripts\activate

(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>python manage.py runserver
Traceback (most recent call last):
  File "C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb\manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb\manage.py", line 13, in main
    raise ImportError(
    ...<3 lines>...
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>django
"django" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>django-admin --version
5.2.1

(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>python manage.py runserver
Traceback (most recent call last):
  File "C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb\manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb\manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb\manage.py", line 13, in main
    raise ImportError(
    ...<3 lines>...
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>pip install django
Collecting django
  Downloading django-5.2.2-py3-none-any.whl.metadata (4.1 kB)
Collecting asgiref>=3.8.1 (from django)
  Using cached asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting sqlparse>=0.3.1 (from django)
  Using cached sqlparse-0.5.3-py3-none-any.whl.metadata (3.9 kB)
Collecting tzdata (from django)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Downloading django-5.2.2-py3-none-any.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 53.3 MB/s eta 0:00:00
Using cached asgiref-3.8.1-py3-none-any.whl (23 kB)
Using cached sqlparse-0.5.3-py3-none-any.whl (44 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, sqlparse, asgiref, django
Successfully installed asgiref-3.8.1 django-5.2.2 sqlparse-0.5.3 tzdata-2025.2

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
June 09, 2025 - 19:37:02
Django version 5.2.2, using settings 'miweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
[09/Jun/2025 19:40:14] "GET / HTTP/1.1" 200 12068
Not Found: /favicon.ico
[09/Jun/2025 19:40:14] "GET /favicon.ico HTTP/1.1" 404 2207
^C
(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>code .

(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
June 09, 2025 - 20:23:00
Django version 5.2.2, using settings 'miweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Not Found: /
[09/Jun/2025 20:23:14] "GET / HTTP/1.1" 404 2881
[09/Jun/2025 20:23:50] "GET /saludo/ HTTP/1.1" 200 17
[09/Jun/2025 20:24:10] "GET /saludo_nombre/ HTTP/1.1" 200 9
[09/Jun/2025 20:24:30] "GET /edad/ HTTP/1.1" 200 9
[09/Jun/2025 20:25:44] "GET /admin/ HTTP/1.1" 302 0
[09/Jun/2025 20:25:45] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4173
[09/Jun/2025 20:25:45] "GET /static/admin/css/base.css HTTP/1.1" 200 22120
[09/Jun/2025 20:25:45] "GET /static/admin/css/login.css HTTP/1.1" 200 951
[09/Jun/2025 20:25:45] "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
[09/Jun/2025 20:25:45] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
[09/Jun/2025 20:25:45] "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
[09/Jun/2025 20:25:45] "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
[09/Jun/2025 20:25:45] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
Not Found: /
[09/Jun/2025 20:25:56] "GET / HTTP/1.1" 404 2881
[09/Jun/2025 20:26:04] "GET /edad/ HTTP/1.1" 200 9
Not Found: /
[09/Jun/2025 20:26:07] "GET / HTTP/1.1" 404 2881
^C
(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>code .

(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>python manage.py runserver
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
June 09, 2025 - 20:40:53
Django version 5.2.2, using settings 'miweb.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

WARNING: This is a development server. Do not use it in a production setting. Use a production WSGI or ASGI server instead.
For more information on production servers see: https://docs.djangoproject.com/en/5.2/howto/deployment/
Not Found: /edad/
[09/Jun/2025 20:41:05] "GET /edad/ HTTP/1.1" 404 2948
Not Found: /edad/felipe/
[09/Jun/2025 20:41:13] "GET /edad/felipe/ HTTP/1.1" 404 2969
[09/Jun/2025 20:41:23] "GET /edad/21/ HTTP/1.1" 200 9
Not Found: /saludo/no,bre/felipe/
[09/Jun/2025 20:41:52] "GET /saludo/no,bre/felipe/ HTTP/1.1" 404 2996
[09/Jun/2025 20:42:08] "GET /saludo/felipe/ HTTP/1.1" 200 11
[09/Jun/2025 20:42:25] "GET /saludo_fijo/ HTTP/1.1" 200 42
Not Found: /
[09/Jun/2025 20:42:39] "GET / HTTP/1.1" 404 2915
[09/Jun/2025 21:13:14] "GET /saludo_fijo/ HTTP/1.1" 200 42
^C
(env) C:\Tinf\programacion\proyectos\desafios_django\semana 1\miweb>cd C:\Tinf\programacion\proyectos\desafios_django

(env) C:\Tinf\programacion\proyectos\desafios_django>git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   semana 1/capturas/terminal entorno virtual.txt
        new file:   semana 1/capturas/terminal2.txt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   semana 1/miweb/miweb/__pycache__/settings.cpython-313.pyc
        modified:   semana 1/miweb/miweb/__pycache__/urls.cpython-313.pyc
        modified:   semana 1/miweb/miweb/settings.py
        modified:   semana 1/miweb/miweb/urls.py
        modified:   semana 1/miweb/principal/views.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        semana 1/miweb/principal/__pycache__/
        semana 1/miweb/principal/migrations/__pycache__/
        semana 1/miweb/principal/urls.py
        semana-2/


(env) C:\Tinf\programacion\proyectos\desafios_django>git add .

(env) C:\Tinf\programacion\proyectos\desafios_django>git status
On branch main
Your branch is up to date with 'origin/main'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   semana 1/capturas/terminal entorno virtual.txt
        new file:   semana 1/capturas/terminal2.txt
        modified:   semana 1/miweb/miweb/__pycache__/settings.cpython-313.pyc
        modified:   semana 1/miweb/miweb/__pycache__/urls.cpython-313.pyc
        modified:   semana 1/miweb/miweb/settings.py
        modified:   semana 1/miweb/miweb/urls.py
        new file:   semana 1/miweb/principal/__pycache__/__init__.cpython-313.pyc
        new file:   semana 1/miweb/principal/__pycache__/admin.cpython-313.pyc
        new file:   semana 1/miweb/principal/__pycache__/apps.cpython-313.pyc
        new file:   semana 1/miweb/principal/__pycache__/models.cpython-313.pyc
        new file:   semana 1/miweb/principal/__pycache__/urls.cpython-313.pyc
        new file:   semana 1/miweb/principal/__pycache__/views.cpython-313.pyc
        new file:   semana 1/miweb/principal/migrations/__pycache__/__init__.cpython-313.pyc
        new file:   semana 1/miweb/principal/urls.py
        modified:   semana 1/miweb/principal/views.py
        new file:   semana-2/READme.md
        new file:   semana-2/Semana_2_Guia_Django.pdf
        new file:   semana-2/urls_Miweb.py
        new file:   semana-2/urls_app.py
        new file:   semana-2/views.py


(env) C:\Tinf\programacion\proyectos\desafios_django>git commit -m "Semana 2, urls.py + views.py modificacion de rutas fijas y personalizadas, + READme.md"
[main 0a847c4] Semana 2, urls.py + views.py modificacion de rutas fijas y personalizadas, + READme.md
 20 files changed, 206 insertions(+), 2 deletions(-)
 create mode 100644 semana 1/capturas/terminal2.txt
 create mode 100644 semana 1/miweb/principal/__pycache__/__init__.cpython-313.pyc
 create mode 100644 semana 1/miweb/principal/__pycache__/admin.cpython-313.pyc
 create mode 100644 semana 1/miweb/principal/__pycache__/apps.cpython-313.pyc
 create mode 100644 semana 1/miweb/principal/__pycache__/models.cpython-313.pyc
 create mode 100644 semana 1/miweb/principal/__pycache__/urls.cpython-313.pyc
 create mode 100644 semana 1/miweb/principal/__pycache__/views.cpython-313.pyc
 create mode 100644 semana 1/miweb/principal/migrations/__pycache__/__init__.cpython-313.pyc
 create mode 100644 semana 1/miweb/principal/urls.py
 create mode 100644 semana-2/READme.md
 create mode 100644 semana-2/Semana_2_Guia_Django.pdf
 create mode 100644 semana-2/urls_Miweb.py
 create mode 100644 semana-2/urls_app.py
 create mode 100644 semana-2/views.py

(env) C:\Tinf\programacion\proyectos\desafios_django>git push
Enumerating objects: 41, done.
Counting objects: 100% (41/41), done.
Delta compression using up to 12 threads
Compressing objects: 100% (28/28), done.
Writing objects: 100% (28/28), 32.48 KiB | 1.91 MiB/s, done.
Total 28 (delta 8), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (8/8), completed with 6 local objects.
To https://github.com/SilverPhantomX/desafios-django-.git
   2e502ab..0a847c4  main -> main

(env) C:\Tinf\programacion\proyectos\desafios_django>git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   semana-2/READme.md

no changes added to commit (use "git add" and/or "git commit -a")

(env) C:\Tinf\programacion\proyectos\desafios_django>git add
Nothing specified, nothing added.
hint: Maybe you wanted to say 'git add .'?
hint: Disable this message with "git config set advice.addEmptyPathspec false"

(env) C:\Tinf\programacion\proyectos\desafios_django>git add .

(env) C:\Tinf\programacion\proyectos\desafios_django>git commit -m "desafios Django"
[main 4f861e2] desafios Django
 1 file changed, 25 insertions(+)

(env) C:\Tinf\programacion\proyectos\desafios_django>git push
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 735 bytes | 735.00 KiB/s, done.
Total 4 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/SilverPhantomX/desafios-django-.git
   0a847c4..4f861e2  main -> main

(env) C:\Tinf\programacion\proyectos\desafios_django>